### ISSUE TITLE
failures-mining 

### ISSUE THREAD

**Issue by hsnellen** [azgs/azlibrary_database#24]
Curious about a failure and how we can remedy it,  processingNotes states: "Problem inserting azgs metadata record: errorL syntaz error at or near \",\""
One example is upload ID 19546
Attached is metadata file for failure json
[failure.zip](https://github.com/azgs/azlibrary_database/files/3128638/failure.zip)

**Comment by NoisyFlowers** [comment]
That error is indeed cryptic. So much so that I fixed it 24 days ago. The error should read 'Invalid bounding box in metadata'.

Apparently, I never issued a pull on this to dev. I just did that now.

It should be safe to assume that for all collections that failed due to the old message, their bounding boxes need to be filled in/cleaned up.

**Comment by hsnellen** [comment]
Ah awesome, thanks!
