### ISSUE TITLE
Adding unique keywords as a dictionary

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#50]
Although we can search the keywords using the metadata endpoint, it might be nice to have /dicts/keywords route that returns DISTINCT and COUNT for keyword terms.

This suggestion came from @Lbookman

**Comment by NoisyFlowers** [comment]
I've been fiddling with queries, trying to figure out how best to get at the keywords in the json. Here's what I've come up with so far. Let me know if I'm making incorrect assumptions about the intended function.

### For DISTINCT
Probably an API call like this:
```
http://apihost/api/v1/dicts/keywords
```
This would return a list of all the keywords in type:name format. These could also be formatted as urls in the format for COUNT, as below.

The query for this would look something like:
```
SELECT 
	distinct (obj.val->>'type')||':'||(obj.val->>'name') AS keyword
FROM   
	metadata.azgs m,
	jsonb_array_elements(m.json_data->'keywords') obj(val) 
order by 
	keyword asc
```

### For COUNT
Probably via API calls like this:
```
http://apihost/api/v1/dicts/keywords?type=x
http://apihost/api/v1/dicts/keywords?type=x&name=y
```
The former would return all the names for a given type, probably as urls in the format of the latter. The latter would return the number of collections that contain the keyword type:name.

The query for the list of types would be something like:
```
SELECT 
	distinct (obj.val->>'type') AS type
FROM   
	metadata.azgs m,
	jsonb_array_elements(m.json_data->'keywords') obj(val) 
order by 
	type asc
```
2024-05-06 edit:
```
SELECT 
	distinct (obj.val->>'name') AS name
FROM   
	metadata.azgs m,
	jsonb_array_elements(m.json_data->'keywords') obj(val) 
where
	obj.val->>'type' = 'temporal'
order by 
	name asc
```

The query for the count would be something like:
```
SELECT 
	--m.metadata_id, 
	--obj.val->>'name' AS keyword
	count(*)
FROM   
	metadata.azgs m
	JOIN LATERAL 
		jsonb_array_elements(m.json_data->'keywords') AS obj(val) 
	ON 
		obj.val->>'type' = 'theme' AND
		obj.val->>'name' = 'granites'
WHERE  
	m.json_data->'keywords' @> '[{"type":"theme", "name":"granites"}]';
```

Note: That redundant WHERE clause is to enable use of an index. See https://dba.stackexchange.com/questions/127689/how-to-get-particular-object-from-jsonb-array-in-postgresql.

Or the api calls could use path parameters rather than query parameters:
```
http://apihost/api/v1/dicts/keywords/<type>
http://apihost/api/v1/dicts/keywords/<type>/<name>
```
As before, the former would return all the names for a given type, probably as urls in the format of the latter. The latter would return the number of collections that contain the keyword type:name.

**Comment by aazaff** [comment]
It looks like you did a lot of work on this one, but Il et it slip through the cracks. I prefer the former rather then the latter.

**Comment by aazaff** [comment]
I consider this very low priority to pick back up again, but am leaving this issue open, because keyword mapping may be relevant as we being integration with ScienceBase

**Comment by NoisyFlowers** [comment]
This is implemented in
azgs/azlibrary_api@fe9fea9a78250f9aeb3422975fe410444c556c52
azgs/azlibrary_api@95532944a6267b2aa84bbaffb615ae92f63db3fb
azgs/azlibrary_api@03748aa4590c9764c313984040ef2a63d40d3ddc

On weave branch, running on dev
