### ISSUE TITLE
Items that manually need to be branched

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#83]
Now that #40 is nearing completion, we will need to do a 1-time retroactive re-lineage-ing of collections that need to be split or merged.

I am keeping a record here of ones that require this.

Parent: ADGM-1552430032775-571
Children: ADGM-1599757563530-90, ADGM-1599757847981-629, ADGM-1599757988809-181, ADGM-1599757010886-934
> All the children collections above are currently marked as private

Parents: AOFR-1552430900055-986, AOFR-1552427003007-158
Child: ADGM-1572451811712-105

Parent: AOFR-1552426800481-349
Children: ADGM-1669753102646-397, ADGM-1669754756906-455, ADGM-1669755388590-632, ADGM-1669755813860-424

**Comment by LeahZaitlin** [comment]
Parent: AOFR-1552429540446-674
Children: ADGM-1669743185563-334, ADGM-1669744320770-749, ADGM-1669738444900-277, ADGM-1669739462175-374, ADGM-1669741179489-559

~~Parent: AOFR-1552426800481-349
Children: ADGM-1669753102646-397, ADGM-1669754756906-455, ADGM-1669755388590-632, ADGM-1669755813860-424~~
> duplicated of above

**Comment by NoisyFlowers** [comment]
Cool! Nice to see that this will get used right away.

**Comment by NoisyFlowers** [comment]
I want to make sure I understand your terminology above. By "parent" you mean predecessor, and by "child" you mean successor. Is this correct?

**Comment by aazaff** [comment]
Yes, exactly. Sorry for the inconsistency.

**Comment by NoisyFlowers** [comment]
This seems like something that could come up once in a while: needing to patch the supersedes of a previously created collection. 

So, rather than just manually fix these, I changed the main db trigger that maintains sync between metadata.azgs and public.collections and public.lineage to also maintain the metadata in previous collections. 

This enabled me to change the Patch functionality of azlibrary_webclient (the admin form) to allow changing of supersedes.

Also allowed me to remove some code from azgsMetadata.js in azlibrary_database/azlibAdd that always felt a bit sore thumb.

This is all in
c2cc6b3a0ead9406bf6dfa49e3fe7c51da48fac5
4c7084d62c0037f8a2ffdc1ae87a7a596f0c8840
d461e52c3eba89e50a133bcfe2f516aa8f7de793
e7daa638a7adf15297b33b552fd18a77adea2a86
1f05730e54998135dc2fdd170219b513c26271a9
azgs/azlibrary_webclient@b66cca00b328aa5cf310f1a4ed124398ba8f710c

Not merged to master, running on dev

**Comment by NoisyFlowers** [comment]
Also note: I've used this on dev to modify

Parent: ADGM-1552430032775-571
Children: ADGM-1599757563530-90, ADGM-1599757847981-629, ADGM-1599757988809-181, ADGM-1599757010886-934

and

Parents: AOFR-1552430900055-986, AOFR-1552427003007-158
Child: ADGM-1572451811712-105

I'm leaving the rest as testpieces for others to verify the new functionality.

**Comment by NoisyFlowers** [comment]
Also note: in the form, Supersedes editing is far down, after Bounding Box, just before Files. Didn't feel like the sort of thing we want to draw attention to.

**Comment by aazaff** [comment]
Sounds slick!
